language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    secure: CRTJgZah7Owh+Yn4hkksiY/2khw5mY/eKsGbPKVxFPhhkNT/8Wq6N8FBbR7qubWhs8+xejmUvgYvSGOzN91JyYUQLXtGnYl6fk4hQkVwpnwonVE55Oo7zVZlEJJ4UMpAw5QExCMBs3Gku8nNAPmL8eagXpChkKaLd3VlPDEVSHk=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/333a592089a1fcf68f30
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
